version: '3.3'
services:
    rabbitmq:
        hostname: my-rabbit
        container_name: some-rabbit
        ports:
            - '15672:15672'
            - '5672:5672'
        image: 'rabbitmq:3-management'
